# Generated by Django 5.1.2 on 2024-11-06 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_auto_20241106_2225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="last_hit_time",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
